# Generated by Django 3.2.13 on 2022-05-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsondataferretexampleapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="data_private",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="data_public",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="project",
            name="data_private",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="project",
            name="data_public",
            field=models.JSONField(default=dict),
        ),
    ]
