# Generated by Django 3.2.13 on 2022-05-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsondataferret", "0002_jsondataferret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edit",
            name="data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="record",
            name="cached_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="record",
            name="cached_jsonschema_validation_errors",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
